-- Allow AgentThread rows without a logged-in user (for anonymous chat sessions
-- claimed at sign-in) and add an index for cookie-based lookup.
--
-- Hand-written rather than generated by `prisma migrate dev` because the
-- existing migration history fails shadow-DB validation (some prior migrations
-- alter tables that no migration creates). This migration was applied to dev
-- via `prisma db push`; on `main` it should be applied via raw SQL or
-- `db push` as well until the broken history is rebaselined.

-- DropForeignKey (recreated below as nullable)
ALTER TABLE "AgentThread" DROP CONSTRAINT "AgentThread_userId_fkey";

-- AlterColumn
ALTER TABLE "AgentThread" ALTER COLUMN "userId" DROP NOT NULL;

-- AddColumn
ALTER TABLE "AgentThread" ADD COLUMN "anonymousId" TEXT;

-- CreateIndex
CREATE INDEX "AgentThread_anonymousId_idx" ON "AgentThread"("anonymousId");

-- AddForeignKey (nullable userId, cascade on delete)
ALTER TABLE "AgentThread" ADD CONSTRAINT "AgentThread_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
