// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config as loadEnv } from "dotenv";

// Production scripts set AGORA_ENV_FILE=.env.production.local before invoking Prisma.
// Default dev path loads .env.local first (do not set AGORA_ENV_FILE for local work).
const envFile = process.env.AGORA_ENV_FILE?.trim();
if (envFile) {
  loadEnv({ path: envFile, override: true });
} else {
  loadEnv({ path: ".env.local" });
  loadEnv(); // also load .env if present
}

import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Use DIRECT_URL (unpooled) for migrations when available — Neon's pgbouncer
    // doesn't support the session-level features Prisma Migrate needs.
    // Falls back to DATABASE_URL for non-Neon setups.
    url: process.env["DIRECT_URL"] || process.env["DATABASE_URL"],
  },
});
