// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config as loadEnv } from "dotenv";
loadEnv({ path: ".env.local" });
loadEnv(); // also load .env if present
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Use DIRECT_URL (unpooled) for migrations when available — Neon's pgbouncer
    // doesn't support the session-level features Prisma Migrate needs.
    // Falls back to DATABASE_URL for non-Neon setups.
    url: process.env["DIRECT_URL"] || process.env["DATABASE_URL"],
  },
});
